apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
spec:
  project: default
  source:
    repoURL: git@github.com:thanad/n8n.git
    path: helm/n8n
    helm:
      releaseName: n8n
      valueFiles:
        - values.yaml
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
      - /data/postgres-password
  destination:
    name: in-cluster
    namespace: default
